#!/bin/sh -e
### BEGIN INIT INFO
# Provides:          wolfbot
# Required-Start:    $local_fs
# Required-Stop:     $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Wolfbot
# Description:       Wolfbot boot scripts
### END INIT INFO

case "$1" in
start|reload|force-reload|restart)
        /wolfbot/setup/setup_all.sh
        ;;
stop)
        exit 0
        ;;
*)
        echo "Usage: /etc/init.d/wolfbot {start|stop}"
        exit 1
        ;;
esac

exit 0

